### ISSUE TITLE
Data/File not found

### ISSUE THREAD

**Issue by amitsadhu** [hammer-mt/thumb#3]
Getting the following error while running on Google Colab:

[<ipython-input-8-9d04379ba393>](https://localhost:8080/#) in <cell line: 12>()
     10 
     11 # generate the responses
---> 12 test = thumb.test([prompt_a, prompt_b])

2 frames
[/usr/local/lib/python3.10/dist-packages/thumb/core.py](https://localhost:8080/#) in _load_data(self, file_path)
    316 
    317             else:
--> 318                 raise FileNotFoundError(f"No data found for tid: {self.tid}")
    319 
    320     def _read_from_csv(self, csv_file_path):

FileNotFoundError: No data found for tid: tell me a joke

It seemed to work seamlessly a week ago.

**Comment by hammer-mt** [comment]
Sorry about this, ran into a few issues - working on fixing

**Comment by amitsadhu** [comment]
No worries! Happy to help, if required.

**Comment by hammer-mt** [comment]
This is fixed now (hopefully!)

**Comment by amitsadhu** [comment]
Working now, thanks!
